Feat/random greeting
cancelei/hello-rails-react2 pull request #1
Opened 2023-11-08 19:54 UTC by cancelei

Hello reviewer!

- Implement a connection between a Ruby on Rails back-end and React front-end.
- Post gress database (Using .env file, that one needs to fill in to use.)
- API endpoint that generates greetings.
- Static front end that is pointed to the root.

Happy review!

2023-11-08 22:51 UTC, OLIPLICHE requested changes
Hi @cancelei, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Used Webpack with jsbundling-rails 👍 
- Created Rails app 👍 
- The project has a Postgres database 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 22:51 UTC, OLIPLICHE commented on app/javascript/components/GreetingContext.js
> +
- [ ] Hi, You have done a great job in displaying random Greating, But I believe that you did not follow well the requirements. Learning objectives here is to **implement a connection between a Ruby on Rails back-end and a React front-end.** 
- The requirement says: **Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.**  I would advise you to follow this requirement.
- The picture below is the feedback I got when I changed the API in your react app to your localhost (a connection between a Ruby on Rails back-end and a React front-end)
![Capture](https://github.com/cancelei/hello-rails-react2/assets/63972670/598ec0b4-1fc8-4546-8537-c9a709df963f)

2023-11-10 00:18 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @cancelei, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well adding a reducer, store and action creators as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 03:08 UTC, merged

2023-12-13 14:16 UTC, gemmen29 reviewed
Hi @cancelei, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._